import { EventEmitter, ChangeDetectorRef, OnInit, TemplateRef } from '@angular/core';
import { SortDirection, SortType, SelectionType, TableColumn } from '../../types';
import { FontChangesService } from '../../services';
export declare class DataTableHeaderCellComponent implements OnInit {
    private cd;
    private fontChangesService;
    sortType: SortType;
    sortAscendingIcon: string;
    sortDescendingIcon: string;
    isTarget: boolean;
    targetMarkerTemplate: any;
    targetMarkerContext: any;
    _allRowsSelected: boolean;
    clickedHeader: string;
    headerFont: string;
    clickedColumn: string;
    allRowsSelected: boolean;
    selectionType: SelectionType;
    column: TableColumn;
    headerHeight: number;
    sorts: any[];
    sort: EventEmitter<any>;
    select: EventEmitter<any>;
    columnContextmenu: EventEmitter<{
        event: MouseEvent;
        column: any;
    }>;
    readonly columnCssClasses: any;
    readonly name: string;
    readonly minWidth: number;
    readonly maxWidth: number;
    readonly width: number;
    readonly isCheckboxable: boolean;
    sortFn: any;
    sortClass: string;
    sortDir: SortDirection;
    selectFn: any;
    sortHeaderFn: any;
    headerTemplate: TemplateRef<any>;
    cellContext: any;
    private _column;
    private _sorts;
    constructor(cd: ChangeDetectorRef, fontChangesService: FontChangesService);
    onContextmenu($event: MouseEvent): void;
    calcSortDir(sorts: any[]): any;
    ngOnInit(): void;
    onSort(): void;
    onSortHeader(header: string): void;
    calcSortClass(sortDir: SortDirection): string;
}
